site_name: My Docs
dev_addr: 0.0.0.0:8000

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Agent Dev: agent-dev/
  - Algorithm: algo/
  - Database: db/
  - Study Path: dev-study-path/
  - Project:
    - TrapMap:
      - Quick Start: project/trapmap/快速了解.md
      - Selection: project/trapmap/选型.md
      - Requirements: project/trapmap/需求和思考.md
      - Pitfalls: project/trapmap/踩坑/
      - Docs: project/trapmap/docs/
    - Archlinux Missionary:
      - Quick Start: project/archlinux-missionary/快速了解.md
      - Selection: project/archlinux-missionary/选型.md
      - Requirements: project/archlinux-missionary/需求和思考.md
      - Status: project/archlinux-missionary/现状与目标差异清单.md
      - Packages: project/archlinux-missionary/包说明与选型附录.md
      - Docs: project/archlinux-missionary/docs/
